name: rag-trl-calculator
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.13.0
  - pip
  - pip:
    - fastapi==0.115.9
    - uvicorn==0.34.2
    - pydantic==2.11.3
    - numpy==2.2.5
    - torch==2.7.0
    - transformers==4.46.0
    - accelerate==1.6.0
    - chromadb==1.0.7
    - python-docx==1.1.2
    - PyPDF2==3.0.1
    - sentence-transformers==4.1.0
    - langchain-text-splitters==0.3.8